[project]
name = "cracktify-project"
version = "2.0.0"
description = "A crack detection app built with Flet and PyJNIus."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
    "flet>=0.80.4",
    "pyjnius==1.6.1",
    "pillow>=10.4.0",
    "flet-video==0.80.5",
    "flet-lottie==0.80.5",
]

[dependency-groups]
dev = [
    "flet-cli>=0.80.4",
    "flet-desktop>=0.80.4",
    "flet-web>=0.80.4"
]

[tool.flet]
org = "com.mycompany"
product = "Cracktify"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"

assets = ["src/assets"]

compile.app = true
compile.packages = true
compile.cleanup = true

[tool.flet.android.permissions]
permissions = [
    "android.permission.READ_MEDIA_IMAGES",
    "android.permission.READ_MEDIA_VIDEO",
    "android.permission.READ_MEDIA_AUDIO",
    "android.permission.READ_EXTERNAL_STORAGE"
]

[tool.flet.app]
path = "src"


